### ISSUE TITLE
Shape Coverage should be MULTIPLE elements but isn't

### ISSUE THREAD

**Issue by graybeal** [matthewhorridge/cedar-cli#4]
The indented 'Shape Coverage' should be multiple elements (*inside* the Spatial Coverage element); it looks like an indented element in the template, but it isn't multiple when filling it out.

There's no indication that the element is multiple in the JSON. I think this is what it looks like when an element is multiple, yes?
```
"DataStream": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "@id": "https://repo.metadatacenter.org/template-elements/56233160-380f-4b6d-95dc-690994b4bada",
        "@type": "https://schema.metadatacenter.org/core/TemplateElement",
        "@context": {
…
```

**Comment by matthewhorridge** [comment]
This is fixed now
