### ISSUE TITLE
Handle textarea field types

### ISSUE THREAD

**Issue by graybeal** [matthewhorridge/cedar-cli#6]
A few field types are now textarea (to allow paragraph and new line entry). Please accommodate.

**Comment by matthewhorridge** [comment]
Working as expected with the latest spreadsheet.  Just to confirm the type in the spreadsheet is "textarea".  This is the same type as the underlying inputType in CEDAR but the CEDAR UI calls this "paragraph" (which seems odd)

<img width="916" alt="image" src="https://user-images.githubusercontent.com/488607/184038251-b519026e-8cd8-467c-8120-4598a4008f11.png">
